### ISSUE TITLE
Implementar Tabla de Contenido Usando la propiedad expuesta en #421 y #422

### ISSUE THREAD

**Issue by andresperezcera** [PyBAQ/website#424]
# Solicitud de mejora en sitio web PyBAQ

Implementar Tabla de Contenido Usando la propiedad expuesta en #421 y #422. 

El plugin [lektor-markdown-header-anchors](https://github.com/lektor/lektor-markdown-header-anchors) habilita la propiedad `.toc` que permite usar plantillas para generar tablas de contenido basadas en campos de markdown. 

![image](https://github.com/PyBAQ/website/assets/11465755/e0c87d24-e04a-4608-b9d6-1ac6313122fa)

- [x] Modificar modelo de BlogPost agregando nuevo campo booleano de TDC (Tabla de Contenido).
- [x] Agregar una TDC a la plantilla usando el ejemplo mostrado en este [link](https://github.com/lektor/lektor-markdown-header-anchors#in-templates)
- [x] Modificar plantilla de articulo de blog para incluir TDC opcional.
- [x] Agregar alt para "toc" databag de settings.
- [ ] Crear maqueta de articulo con TDC.
- [ ] Crear CSS de TDC para artículos del Blog

## Ventajas

En articulos relativamente complejos/largos facilita la navegación. Si decidimos generar contenido a manera de instructivos o publicaciones fuera del blog, serán necesario contar con la posibilida de generar tablas de contenido.

## Desventajas

Ninguna. No impacta ningún otro elemento de la página.

**Comment by andresperezcera** [comment]
@Scot3004 @pyjavo No tengo ni idea de dónde empezar con el SCSS de la tabla de contenido. Necesito que alguien me dé una mano para entender como está pensado.

**Comment by Scot3004** [comment]
Las cosas sticky suelen ser problemáticas, en el pr que vi que tenias abierto por ejemplo los títulos aparecen tapados por el menú de navegación, creo que deberíamos partir esta tarea en 2, 
- Implementar la tabla de navegación, y la ponemos en el principio del articulo, tal como se ve en el PR, incluyendo agregar un offset para que no se tapen los títulos
- Hacer la tabla de contenidos flotante, hay que hacer una nueva template con los nuevos diseños cuando deba aparecer la tabla de contenido, y para esto lo mejor es apoyarnos en figma para saber como se debería ver el resultado final

**Comment by andresperezcera** [comment]
> * Implementar la tabla de navegación, y la ponemos en el principio del articulo, tal como se ve en el PR, incluyendo agregar un offset para que no se tapen los títulos
 
Ya agregué el offset


> * Hacer la tabla de contenidos flotante, hay que hacer una nueva template con los nuevos diseños cuando deba aparecer la tabla de contenido, y para esto lo mejor es apoyarnos en figma para saber como se debería ver el resultado final

Sip, a eso me refiero con maqueta. Pero ya no tengo acceso al Figma de la pagina. Sin embargo he hecho varios ajustes en #424, se ve decente.

**Comment by pyjavo** [comment]
Concuerdo con @Scot3004 en ambos puntos 😅 

+1 para apoyarnos en figma (se le puede dar acceso a Andrés si no lo tiene). La idea es estar de acuerdo en el diseño antes de que se escriba la primera línea de CSS (o SCSS).

+1 a que se divida esta tarea en dos. Luego se va a volver algo complejo de revisar

**Comment by andresperezcera** [comment]
@Scot3004 @pyjavo Ok, guardo aqui los ajustes hechos en scss.

- [ ] Revertiré el ultimo commit y limitaré el alcance de #424.

Los cambios que quedan: 
La plantilla `blog-post.html`
````jinja
    <nav class="tdc">
      <h2>{{bag('settings', alt, 'toc')}}</h6>
      <ul>
        {% for item in this.body.toc recursive %}
        <li><a href="#{{ item.anchor }}">{{ item.title }}</a>
          {%if item.children %}
          <ul>{{ loop(item.children) }}</ul>
          {% endif %}
        </li>
        {% endfor %}
      </ul>
    </nav>
````

Archivo `_base.scss` el siguiente codigo en la parte superior.
````scss
html {
  scroll-padding-top: 80px; /* height of sticky header */
  scroll-behavior: smooth;
}
````

En archivo en databags `settings.json`.
````json
{
  "es": {
    "toc": "Contenido"
  },
  "en": {
    "toc": "Content"
  }
}
````

- [ ] Crearé Issue con las tareas de diseño en figma de la apariencia y la implementación de dicho diseño en scss/css, documento la propuesta original:

En archivo `_blog.scss` el siguiente codigo dentro de la clave `blog-post`.
````scss
nav{
    border: none;
    
    margin-bottom: 1em;
    padding: 20px;
    background-color: $blue-opacity-rgba;

    @media (min-width: 1550px) {
      display: table;
      position: fixed;
      right: 25px;
      max-width: 325px;
      border-radius: 25px;
      top: 25px;
    }
    @media (max-width: 1549px) {
      border-radius: 25px;
      display:-webkit-flex;
      -webkit-justify-content:center;
      display:flex;
      width: auto;
      margin: auto;
      max-width: 800px;
    }	
    
    h2{
      margin-bottom: 10px;
      font-size: 1.5rem;
    }

    li, ul, ul li{
      list-style: outside none none !important;
      font-size: 1rem;
    }

    a {
      color: $white;
      font-size: 1rem;
      &:hover {
        color: $yellow-hover;
      }
    }
  }
````



Tambien importante:
- [ ] Crearé un segundo issue ya que el codespace actual no incluye herramientas para compilación de scss a css por defecto.

Todo este documento para dejar claro el resultado de la discusión.
