### ISSUE TITLE
Implementar diseño TDC en scss/css

### ISSUE THREAD

**Issue by andoresuperesu** [PyBAQ/website#427]
# Solicitud de mejora en sitio web PyBAQ

Esto completa la incorporación de TDC en PyBAQ

## Ventajas

Se discutieron en #421 y #424

Propuesta original de #425 separada por falta de diseño:

En archivo `_blog.scss` el siguiente codigo dentro de la clave `blog-post`.
````scss
nav{
    border: none;
    
    margin-bottom: 1em;
    padding: 20px;
    background-color: $blue-opacity-rgba;

    @media (min-width: 1550px) {
      display: table;
      position: fixed;
      right: 25px;
      max-width: 325px;
      border-radius: 25px;
      top: 25px;
    }
    @media (max-width: 1549px) {
      border-radius: 25px;
      display:-webkit-flex;
      -webkit-justify-content:center;
      display:flex;
      width: auto;
      margin: auto;
      max-width: 800px;
    }	
    
    h2{
      margin-bottom: 10px;
      font-size: 1.5rem;
    }

    li, ul, ul li{
      list-style: outside none none !important;
      font-size: 1rem;
    }

    a {
      color: $white;
      font-size: 1rem;
      &:hover {
        color: $yellow-hover;
      }
    }
  }
````

## Desventajas

Ninguna
